In [17]:
#1st question:
#1.Write python program:
#a)Convert two lists into a dictionary
names_a = ['Lily', 'Daisy', 'Jack', 'Henry']
value_a = [1, 2, 3, 4,]

dict_a = dict(zip(names_a, value_a))
print(dict_a)

#b)Merge two Python dictionaries into one
dict_b_1 ={'a': 1, 'b': 2}
dict_b_2 ={'c': 3, 'd': 4}

dict_b_1.update(dict_b_2)
print(dict_b_1)

#c)Print the value of key ‘history’ from the below dict
dict_c = {
    "class": {
        "student": {
            "name": "Mike",
            "marks": {
                "physics": 70,
                "history": 80
            }
        }
    }
}
history_marks = dict_c["class"]["student"]["marks"]["history"]
print(history_marks)

#d)Initialize dictionary with default values
keys_d = ["a", "b", "c"]
value_d = 0

dict_d = dict.fromkeys(keys_d, value_d)
print(dict_d)

#e)Create a dictionary by extracting the keys from a given dictionary
dict_e = {
    "name": "Alice",
    "age": 30,
    "salary": 75000,
    "city": "New york",
    "occupation": "Engineer"}
keys_to_extract = ["name", "salary"]
extracted_keys = {key: dict_e[key] for key in keys_to_extract}
print(extracted_keys)

#f)Delete a list of keys from a dictionary
dict_f = {
    "name": "Bob",
    "age": 25,
    "salary": 50000,
    "city": "New york",
    "occupation": "Sales"}
keys_to_delete = ["age", "salary"]
for key in keys_to_delete:
    dict_f.pop(key, None)
print(dict_f)
#g)Check if a value exists in a dictionary
dict_g = {'A': 1, 'B': 2, 'C': 3, 'D': 4}
if 2 in dict_g.values():
    print("2 exists in the dictionary")
else:
    print("2 does not exist in the dictionary")

#h)Rename key of a dictionary
dict_h = {
    'name': 'Charlie',
    'age': '23',
    'salary': '80000',
    'city': 'New York',
    'occupation': 'Engineer'}
dict_h['department'] = dict_h.pop('occupation')
print(dict_h)

#i)Get the key of a minimum value from the following dictionary
dict_i = {
    'Physics': 82,
    'Math': 65,
    'history': 75
}
min_value = min(dict_i.values())
min_key = min(dict_i, key=dict_i.get)
print(min_key)
#j)Change value of a key in a nested dictionary
dict_j = {
    'emp1': {
        'name': 'Bob',
        'salary': 75000
    },
    'emp2': {
        'name': 'Alice',
        'salary': 80000
    },
    'emp3': {'name': 'Charlie',
             'salary': 65000
    }
}
dict_j['emp3']['salary'] = 85000
print(dict_j)



#2.Write a Python program that counts the number of times characters appear in a text paragraph.
text = "Python dictionaries are ordered and can not contain duplicate keys."
char_count = {}
for char in text:
    if char in char_count:
        char_count[char] += 1
    else:
        char_count[char] = 1
print(char_count)

#3.Write a program using a dictionary containing keys starting from 1 and values​​ containing prime numbers less than a value N.
N = 10
prime_numbers = {}

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

key_counter = 1
for num in range(N):
    if is_prime(num):
        prime_numbers[key_counter] = num
        key_counter += 1

print(prime_numbers)

{'Lily': 1, 'Daisy': 2, 'Jack': 3, 'Henry': 4}
{'a': 1, 'b': 2, 'c': 3, 'd': 4}
80
{'a': 0, 'b': 0, 'c': 0}
{'name': 'Alice', 'salary': 75000}
{'name': 'Bob', 'city': 'New york', 'occupation': 'Sales'}
2 exists in the dictionary
{'name': 'Charlie', 'age': '23', 'salary': '80000', 'city': 'New York', 'department': 'Engineer'}
Math
{'emp1': {'name': 'Bob', 'salary': 75000}, 'emp2': {'name': 'Alice', 'salary': 80000}, 'emp3': {'name': 'Charlie', 'salary': 85000}}
{'P': 1, 'y': 2, 't': 5, 'h': 1, 'o': 5, 'n': 7, ' ': 9, 'd': 5, 'i': 5, 'c': 4, 'a': 6, 'r': 4, 'e': 6, 's': 2, 'u': 1, 'p': 1, 'l': 1, 'k': 1, '.': 1}
{1: 2, 2: 3, 3: 5, 4: 7}

In [4]:
#2nd question:
#Restructuring the company data: Suppose you have a dictionary that contains information about employees at a company.
#Each employee is identified by an ID number, and their information includes their name, department, and salary.
#You want to create a nested dictionary that groups employees by department so that you can easily see the names and salaries of all employees in each department.

#Write a Python program that when given a dictionary, employees, outputs a nested dictionary, dept_employees, which groups employees by department.
dept_employees = {}
employees = {
    '1001': {'name': 'Alice', 'department': 'Engineering', 'salary': 75000},
    '1002': {'name': 'Bob', 'department': 'Sales', 'salary': 50000},
    '1003': {'name': 'Charlie', 'department': 'Engineering', 'salary': 80000},
    '1004': {'name': 'Dave', 'department': 'Marketing', 'salary': 60000},
    '1005': {'name': 'Eve', 'department': 'Sales', 'salary': 55000},
}

for emp_id, emp_info in employees.items():
    department = emp_info['department']
    if department not in dept_employees:
        dept_employees[department] = {}
    dept_employees[department][emp_id] = {'name': emp_info['name'], 'salary': emp_info['salary']}

print(dept_employees)

{'Engineering': {'1001': {'name': 'Alice', 'salary': 75000}, '1003': {'name': 'Charlie', 'salary': 80000}}, 'Sales': {'1002': {'name': 'Bob', 'salary': 50000}, '1005': {'name': 'Eve', 'salary': 55000}}, 'Marketing': {'1004': {'name': 'Dave', 'salary': 60000}}}